// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Hm8wKWeRms0t0Tz-41Vc0dneyW9CtSI',
    appId: '1:140173379906:web:2d6b5365df1f69b37a60db',
    messagingSenderId: '140173379906',
    projectId: 'setara-app-ab081',
    authDomain: 'setara-app-ab081.firebaseapp.com',
    storageBucket: 'setara-app-ab081.firebasestorage.app',
    measurementId: 'G-B335R6FM6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Y7W48c2MisU4bcuIojWGaL065xKSlL0',
    appId: '1:140173379906:android:5aec916cf20dee177a60db',
    messagingSenderId: '140173379906',
    projectId: 'setara-app-ab081',
    storageBucket: 'setara-app-ab081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCakhLBYtwlTfMZK-MZqVPJ8UPfMh-HHk0',
    appId: '1:140173379906:ios:3f1a94ad194a17947a60db',
    messagingSenderId: '140173379906',
    projectId: 'setara-app-ab081',
    storageBucket: 'setara-app-ab081.firebasestorage.app',
    androidClientId: '140173379906-38u62gec1gllv9eknu1tkl9cdvti8ea5.apps.googleusercontent.com',
    iosClientId: '140173379906-fcr9qrmfrbng7e5lgpe9vscc6gll257d.apps.googleusercontent.com',
    iosBundleId: 'com.example.setaraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Hm8wKWeRms0t0Tz-41Vc0dneyW9CtSI',
    appId: '1:140173379906:web:b725ecc36c473ecb7a60db',
    messagingSenderId: '140173379906',
    projectId: 'setara-app-ab081',
    authDomain: 'setara-app-ab081.firebaseapp.com',
    storageBucket: 'setara-app-ab081.firebasestorage.app',
    measurementId: 'G-MRP8KRC5WS',
  );

}